# Generated by Django 5.2.3 on 2025-07-03 23:45

import json
from pathlib import Path

from django.db import migrations


def migrate(apps, schema_editor):
    UserAgent = apps.get_model("spodcat_logs", "UserAgent")
    GeoIP = apps.get_model("spodcat_logs", "GeoIP")
    PodcastRequestLog = apps.get_model("spodcat_logs", "PodcastRequestLog")
    PodcastContentRequestLog = apps.get_model("spodcat_logs", "PodcastContentRequestLog")
    PodcastEpisodeAudioRequestLog = apps.get_model("spodcat_logs", "PodcastEpisodeAudioRequestLog")
    PodcastRssRequestLog = apps.get_model("spodcat_logs", "PodcastRssRequestLog")

    json_path = Path(__file__).parent / "../logs.json"
    with json_path.open("rt") as f:
        objects = json.loads(f.read())

    import ipdb; ipdb.set_trace()

    UserAgent.objects.bulk_create(
        [UserAgent(pk=o["pk"], **o["fields"]) for o in objects if o["model"] == "spodcat_logs.useragent"]
    )
    GeoIP.objects.bulk_create(
        [GeoIP(pk=o["pk"], **o["fields"]) for o in objects if o["model"] == "spodcat_logs.geoip"]
    )

    request_logs = {}

    for o in objects:
        if o["model"] == "spodcat_logs.requestlog":
            o["fields"]["user_agent_data_id"] = o["fields"].pop("user_agent_data")
            o["fields"]["geoip_id"] = o["fields"].pop("geoip")
            request_logs[o["pk"]] = o["fields"]

    PodcastRequestLog.objects.bulk_create([
        PodcastRequestLog(
            pk=o["pk"],
            created=o["fields"]["created"],
            podcast_id=o["fields"]["podcast"],
            **request_logs[o["pk"]],
        )
        for o in objects if o["model"] == "spodcat_logs.podcastrequestlog"
    ])
    PodcastContentRequestLog.objects.bulk_create([
        PodcastContentRequestLog(
            pk=o["pk"],
            created=o["fields"]["created"],
            content_id=o["fields"]["content"],
            **request_logs[o["pk"]],
        )
        for o in objects if o["model"] == "spodcat_logs.podcastcontentrequestlog"
    ])
    PodcastRssRequestLog.objects.bulk_create([
        PodcastRssRequestLog(
            pk=o["pk"],
            created=o["fields"]["created"],
            podcast_id=o["fields"]["podcast"],
            **request_logs[o["pk"]],
        )
        for o in objects if o["model"] == "spodcat_logs.podcastrssrequestlog"
    ])

    podcast_episode_audio_request_logs = []
    for o in objects:
        if o["model"] == "spodcat_logs.podcastepisodeaudiorequestlog":
            o["fields"]["episode_id"] = o["fields"].pop("episode")
            podcast_episode_audio_request_logs.append(
                PodcastEpisodeAudioRequestLog(pk=o["pk"], **o["fields"], **request_logs[o["pk"]])
            )
    PodcastEpisodeAudioRequestLog.objects.bulk_create(podcast_episode_audio_request_logs)



class Migration(migrations.Migration):

    dependencies = [
        ('spodcat_logs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
