# Generated by Django 5.2.3 on 2025-07-02 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0002_alter_podcast_categories_and_more'),
        ('spodcat_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='spodcat.podcastcontent', verbose_name='podcast content'),
        ),
        migrations.AlterField(
            model_name='podcastepisodeaudiorequestlog',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_requests', to='spodcat.episode', verbose_name='episode'),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='spodcat.podcast', verbose_name='podcast'),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_requests', to='spodcat.podcast', verbose_name='podcast'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='geoip',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='spodcat_logs.geoip', verbose_name='GeoIP'),
        ),
    ]
