# Generated by Django 5.1.6 on 2025-04-19 20:41

import klaatu_django.db
from django.db import migrations, models

import model_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastContentAudioRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_category', models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True)),
                ('device_name', models.CharField(default=None, max_length=40, null=True)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('path_info', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('referrer', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('referrer_category', models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True)),
                ('referrer_name', models.CharField(default=None, max_length=50, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_host', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('user_agent', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('user_agent_name', models.CharField(default=None, max_length=100, null=True)),
                ('user_agent_type', models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(db_index=True)),
                ('duration_ms', models.IntegerField()),
                ('response_body_size', models.IntegerField(db_index=True)),
                ('status_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(model_mixin.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PodcastContentRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_category', models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True)),
                ('device_name', models.CharField(default=None, max_length=40, null=True)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('path_info', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('referrer', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('referrer_category', models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True)),
                ('referrer_name', models.CharField(default=None, max_length=50, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_host', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('user_agent', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('user_agent_name', models.CharField(default=None, max_length=100, null=True)),
                ('user_agent_type', models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'podcast content page request log',
                'verbose_name_plural': 'podcast content page request logs',
            },
            bases=(model_mixin.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PodcastRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_category', models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True)),
                ('device_name', models.CharField(default=None, max_length=40, null=True)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('path_info', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('referrer', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('referrer_category', models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True)),
                ('referrer_name', models.CharField(default=None, max_length=50, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_host', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('user_agent', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('user_agent_name', models.CharField(default=None, max_length=100, null=True)),
                ('user_agent_type', models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'podcast page request log',
                'verbose_name_plural': 'podcast page request logs',
            },
            bases=(model_mixin.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PodcastRssRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_category', models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True)),
                ('device_name', models.CharField(default=None, max_length=40, null=True)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('path_info', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('referrer', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('referrer_category', models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True)),
                ('referrer_name', models.CharField(default=None, max_length=50, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_host', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('user_agent', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('user_agent_name', models.CharField(default=None, max_length=100, null=True)),
                ('user_agent_type', models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'podcast RSS request log',
                'verbose_name_plural': 'podcast RSS request logs',
            },
            bases=(model_mixin.ModelMixin, models.Model),
        ),
    ]
