# Generated by Django 5.1.6 on 2025-03-02 08:58

import klaatu_django.db
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='path_info',
            field=klaatu_django.db.TruncatedCharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='path_info',
            field=klaatu_django.db.TruncatedCharField(blank=True, max_length=200),
        ),
    ]
