# Generated by Django 5.1.6 on 2025-05-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='podcasts.podcastcontent'),
        ),
        migrations.AddField(
            model_name='podcastepisodeaudiorequestlog',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_requests', to='podcasts.episode'),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='podcasts.podcast'),
        ),
    ]
