# Generated by Django 5.1.6 on 2025-04-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcastcontent'),
        ),
        migrations.CreateModel(
            name='PodcastRssRequestLog',
            fields=[
                ('podcastrequestlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logs.podcastrequestlog')),
            ],
            options={
                'abstract': False,
            },
            bases=('logs.podcastrequestlog',),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast'),
        ),
    ]
