# Generated by Django 5.1.6 on 2025-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='user_agent',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
