# Generated by Django 5.1.6 on 2025-04-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='rss_user_agent_slug',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
