# Generated by Django 5.1.6 on 2025-04-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastrssrequestlog',
            options={'verbose_name': 'podcast RSS request log', 'verbose_name_plural': 'podcast RSS request logs'},
        ),
    ]
