# Generated by Django 5.1.6 on 2025-04-13 21:40

from django.db import migrations, models


def migrate(apps, schema_editor):
    PodcastContentAudioRequestLog = apps.get_model("logs", "PodcastContentAudioRequestLog")
    PodcastContentRequestLog = apps.get_model("logs", "PodcastContentRequestLog")
    PodcastRssRequestLog = apps.get_model("logs", "PodcastRssRequestLog")
    PodcastRequestLog = apps.get_model("logs", "PodcastRequestLog")

    for model in [PodcastContentAudioRequestLog, PodcastContentRequestLog, PodcastRssRequestLog, PodcastRequestLog]:
        model.objects.filter(user_agent_type="bot").update(is_bot=True)


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='device_category',
            field=models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='device_name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='referrer_category',
            field=models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='referrer_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='device_category',
            field=models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='device_name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='referrer_category',
            field=models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='referrer_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='device_category',
            field=models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='device_name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='referrer_category',
            field=models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='referrer_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='device_category',
            field=models.CharField(choices=[('auto', 'Auto'), ('computer', 'Computer'), ('mobile', 'Mobile'), ('smart_speaker', 'Smart Speaker'), ('smart_tv', 'Smart Tv'), ('watch', 'Watch')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='device_name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='referrer_category',
            field=models.CharField(choices=[('app', 'App'), ('host', 'Host')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='referrer_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], default=None, max_length=10, null=True),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
