# Generated by Django 5.1.6 on 2025-05-25 02:31

import klaatu_django.db
from django.db import migrations, models

import utils.model_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastRssRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path_info', klaatu_django.db.TruncatedCharField(blank=True, default='', max_length=50)),
                ('remote_addr', models.GenericIPAddressField(db_index=True, default=None, null=True)),
                ('referrer', klaatu_django.db.TruncatedCharField(blank=True, default='', max_length=100)),
            ],
            bases=(utils.model_mixin.ModelMixin, models.Model),
        ),
    ]
