# Generated by Django 5.1.6 on 2025-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastcontentaudiorequestlog',
            name='remote_host',
        ),
        migrations.RemoveField(
            model_name='podcastcontentrequestlog',
            name='remote_host',
        ),
        migrations.RemoveField(
            model_name='podcastrequestlog',
            name='remote_host',
        ),
        migrations.RemoveField(
            model_name='podcastrssrequestlog',
            name='remote_host',
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('googlebot', 'Googlebot'), ('special_crawler', 'Special Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('googlebot', 'Googlebot'), ('special_crawler', 'Special Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('googlebot', 'Googlebot'), ('special_crawler', 'Special Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('googlebot', 'Googlebot'), ('special_crawler', 'Special Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='referrer_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='user_agent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='referrer_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='user_agent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='referrer_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='user_agent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='referrer_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='user_agent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
