# Generated by Django 5.2.3 on 2025-07-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_podcastrssrequestlog'),
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastRssRequestLog2',
            fields=[
                ('requestlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logs.requestlog')),
                ('created', models.DateTimeField(db_index=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_requests', to='podcasts.podcast')),
            ],
            bases=('logs.requestlog',),
        ),
    ]
