# Generated by Django 5.1.6 on 2025-04-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_podcastcontentaudiorequestlog_device_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Bot'), ('browser', 'Browser'), ('library', 'Library')], db_index=True, default=None, max_length=10, null=True),
        ),
    ]
