# Generated by Django 5.1.6 on 2025-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_podcastcontentaudiorequestlog_rss_user_agent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastcontentaudiorequestlog',
            name='rss_user_agent_slug',
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='rss_user_agent_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='user_agent_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='user_agent_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='user_agent_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='user_agent_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
