# Generated by Django 5.1.6 on 2025-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_useragent_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
