# Generated by Django 5.1.6 on 2025-04-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_podcastrssrequestlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastcontentrequestlog',
            options={'verbose_name': 'podcast content page request log', 'verbose_name_plural': 'podcast content page request logs'},
        ),
        migrations.AlterModelOptions(
            name='podcastrequestlog',
            options={'verbose_name': 'podcast page request log', 'verbose_name_plural': 'podcast page request logs'},
        ),
        migrations.DeleteModel(
            name='EpisodeAudioRequestLog',
        ),
    ]
