# Generated by Django 5.1.6 on 2025-04-22 07:26

from django.db import migrations, models


def migrate(apps, schema_editor):
    PodcastRequestLog = apps.get_model("logs", "PodcastRequestLog")
    PodcastRssRequestLog = apps.get_model("logs", "PodcastRssRequestLog")
    PodcastContentRequestLog = apps.get_model("logs", "PodcastContentRequestLog")
    PodcastContentAudioRequestLog = apps.get_model("logs", "PodcastContentAudioRequestLog")

    for model in [PodcastRequestLog, PodcastRssRequestLog, PodcastContentRequestLog, PodcastContentAudioRequestLog]:
        logs = list(model.objects.filter(remote_addr_category="special_crawler"))
        for log in logs:
            log.remote_addr_category = "unknown"
        model.objects.bulk_update(logs, fields=["remote_addr_category"])


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_podcastcontentaudiorequestlog_remote_host_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('applebot', 'Applebot'), ('bingbot', 'Bingbot'), ('duckduckbot', 'Duckduckbot'), ('facebookbot', 'Facebookbot'), ('googlebot', 'Googlebot'), ('twitterbot', 'Twitterbot'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('applebot', 'Applebot'), ('bingbot', 'Bingbot'), ('duckduckbot', 'Duckduckbot'), ('facebookbot', 'Facebookbot'), ('googlebot', 'Googlebot'), ('twitterbot', 'Twitterbot'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('applebot', 'Applebot'), ('bingbot', 'Bingbot'), ('duckduckbot', 'Duckduckbot'), ('facebookbot', 'Facebookbot'), ('googlebot', 'Googlebot'), ('twitterbot', 'Twitterbot'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='remote_addr_category',
            field=models.CharField(choices=[('applebot', 'Applebot'), ('bingbot', 'Bingbot'), ('duckduckbot', 'Duckduckbot'), ('facebookbot', 'Facebookbot'), ('googlebot', 'Googlebot'), ('twitterbot', 'Twitterbot'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
