# Generated by Django 5.1.6 on 2025-05-21 23:01

import klaatu_django.db
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_requestlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='referrer',
            field=klaatu_django.db.TruncatedCharField(blank=True, default='', max_length=150),
        ),
    ]
