# Generated by Django 5.1.6 on 2025-04-12 22:13

import django.db.models.deletion
import klaatu_django.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_podcastcontentrequestlog_options_and_more'),
        ('podcasts', '0006_alter_podcast_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastContentAudioRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remote_host', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('referer', klaatu_django.db.TruncatedCharField(blank=True, max_length=100)),
                ('path_info', klaatu_django.db.TruncatedCharField(blank=True, max_length=200)),
                ('status_code', models.CharField(max_length=10)),
                ('duration_ms', models.IntegerField()),
                ('response_body_size', models.IntegerField()),
                ('content', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_requests', to='podcasts.podcastcontent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
