# Generated by Django 5.1.6 on 2025-04-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_podcastcontentaudiorequestlog_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcastcontentaudiorequestlog',
            old_name='referer',
            new_name='referrer',
        ),
        migrations.RenameField(
            model_name='podcastcontentrequestlog',
            old_name='referer',
            new_name='referrer',
        ),
        migrations.RenameField(
            model_name='podcastrequestlog',
            old_name='referer',
            new_name='referrer',
        ),
        migrations.RenameField(
            model_name='podcastrssrequestlog',
            old_name='referer',
            new_name='referrer',
        ),
    ]
