# Generated by Django 5.1.6 on 2025-04-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_podcastcontentaudiorequestlog_remote_addr_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='podcastcontentaudiorequestlog',
            table='logs_podcastcontentaudiorequestlog_old',
        ),
        migrations.AlterModelTable(
            name='podcastcontentrequestlog',
            table='logs_podcastcontentrequestlog_old',
        ),
        migrations.AlterModelTable(
            name='podcastrequestlog',
            table='logs_podcastrequestlog_old',
        ),
        migrations.AlterModelTable(
            name='podcastrssrequestlog',
            table='logs_podcastrssrequestlog_old',
        ),
    ]
