# Generated by Django 5.1.6 on 2025-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_podcastcontentaudiorequestlog_rss_user_agent_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('app', 'App'), ('library', 'Library'), ('browser', 'Browser')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('app', 'App'), ('library', 'Library'), ('browser', 'Browser')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('app', 'App'), ('library', 'Library'), ('browser', 'Browser')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='user_agent_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('app', 'App'), ('library', 'Library'), ('browser', 'Browser')], default=None, max_length=10, null=True),
        ),
    ]
