# Generated by Django 5.1.6 on 2025-04-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_podcastcontentaudiorequestlog'),
        ('podcasts', '0006_alter_podcast_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='podcast',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='audio_requests', to='podcasts.podcast'),
            preserve_default=False,
        ),
    ]
