# Generated by Django 5.1.6 on 2025-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_podcastcontentaudiorequestlog_user_agent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='rss_user_agent_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('app', 'App'), ('library', 'Library'), ('browser', 'Browser')], default=None, max_length=10, null=True),
        ),
    ]
