# Generated by Django 5.1.6 on 2025-04-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_podcastcontentaudiorequestlog_table_and_more'),
        ('podcasts', '0003_alter_comment_name_alter_podcast_name_font_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PodcastContentAudioRequestLog',
            new_name='PodcastContentAudioRequestLog2',
        ),
        migrations.RenameModel(
            old_name='PodcastContentRequestLog',
            new_name='PodcastContentRequestLog2',
        ),
        migrations.RenameModel(
            old_name='PodcastRequestLog',
            new_name='PodcastRequestLog2',
        ),
        migrations.RenameModel(
            old_name='PodcastRssRequestLog',
            new_name='PodcastRssRequestLog2',
        ),
    ]
