# Generated by Django 5.2.3 on 2025-07-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_migrate_rss_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PodcastRssRequestLog',
        ),
    ]
