# Generated by Django 5.1.6 on 2025-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_rename_referer_podcastcontentaudiorequestlog_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='response_body_size',
            field=models.IntegerField(db_index=True),
        ),
    ]
