# Generated by Django 5.1.6 on 2025-04-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_rename_podcastcontentaudiorequestlog_podcastcontentaudiorequestlog2_and_more'),
        ('podcasts', '0003_alter_comment_name_alter_podcast_name_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog2',
            name='episode',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_requests2', to='podcasts.episode'),
        ),
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog2',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_requests2', to='podcasts.podcast'),
        ),
        migrations.AlterField(
            model_name='podcastcontentrequestlog2',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests2', to='podcasts.podcastcontent'),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog2',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests2', to='podcasts.podcast'),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog2',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_requests2', to='podcasts.podcast'),
        ),
    ]
