# Generated by Django 5.1.6 on 2025-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_podcastcontentaudiorequestlog_response_body_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='podcastrssrequestlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
