# Generated by Django 5.2.3 on 2025-07-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_delete_podcastrssrequestlog'),
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PodcastRssRequestLog2',
            new_name='PodcastRssRequestLog',
        ),
    ]
