# Generated by Django 5.1.6 on 2025-04-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_podcastcontentaudiorequestlog_podcast'),
        ('podcasts', '0006_alter_podcast_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastcontentaudiorequestlog',
            name='content',
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='episode',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_requests', to='podcasts.episode'),
        ),
    ]
