# Generated by Django 5.1.6 on 2025-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_podcastcontentaudiorequestlog_rss_user_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='user_agent_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='user_agent_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='user_agent_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='podcastrssrequestlog',
            name='user_agent_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
