# Generated by Django 5.1.6 on 2025-04-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_remove_podcastcontentaudiorequestlog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentaudiorequestlog',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
