# Generated by Django 5.1.6 on 2025-04-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_podcastcontentaudiorequestlog_user_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastcontentaudiorequestlog',
            name='rss_user_agent_type',
        ),
        migrations.AddField(
            model_name='podcastcontentaudiorequestlog',
            name='rss_request_log',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.podcastrssrequestlog'),
        ),
    ]
