# Generated by Django 5.1.6 on 2025-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_geoip_useragent_requestlog_podcastcontentrequestlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoip',
            name='hostname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
