# Generated by Django 5.1.6 on 2025-04-23 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20250422_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='geoip',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='logs.geoip'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='user_agent_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='logs.useragent'),
        ),
    ]
