# Generated by Django 5.1.6 on 2025-04-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_requestlog_geoip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastcontentrequestlog2',
            name='content',
        ),
        migrations.RemoveField(
            model_name='podcastrequestlog2',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='podcastrssrequestlog2',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='PodcastContentAudioRequestLog2',
        ),
        migrations.DeleteModel(
            name='PodcastContentRequestLog2',
        ),
        migrations.DeleteModel(
            name='PodcastRequestLog2',
        ),
        migrations.DeleteModel(
            name='PodcastRssRequestLog2',
        ),
    ]
