# Generated by Django 5.1.6 on 2025-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_remove_podcastcontentrequestlog2_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoip',
            name='hostname',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='remote_host',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
