# Generated by Django 5.1.6 on 2025-04-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_remove_geoip_hostname_requestlog_remote_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisodeaudiorequestlog',
            name='rss_request_log',
        ),
        migrations.DeleteModel(
            name='PodcastRssRequestLog',
        ),
    ]
