# Generated by Django 5.1.6 on 2025-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_remove_podcastepisodeaudiorequestlog_rss_request_log_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={},
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['-created'], name='logs__requestlog__created__idx'),
        ),
    ]
