# Generated by Django 5.1.6 on 2025-04-24 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_alter_requestlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcontentrequestlog',
            name='created2',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastepisodeaudiorequestlog',
            name='created2',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastrequestlog',
            name='created2',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
