# Generated by Django 5.1.6 on 2025-04-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_podcastcontentrequestlog_created2_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requestlog',
            name='logs__requestlog__created__idx',
        ),
    ]
