# Generated by Django 5.1.6 on 2025-04-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_remove_requestlog_logs__requestlog__created__idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='created',
        ),
    ]
