# Generated by Django 5.1.6 on 2025-04-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_remove_requestlog_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcastcontentrequestlog',
            old_name="created2",
            new_name="created",
        ),
        migrations.RenameField(
            model_name='podcastepisodeaudiorequestlog',
            old_name="created2",
            new_name="created",
        ),
        migrations.RenameField(
            model_name='podcastrequestlog',
            old_name="created2",
            new_name="created",
        ),
    ]
