# Generated by Django 5.1.6 on 2025-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_remove_podcastcontentrequestlog_created2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentrequestlog',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='podcastepisodeaudiorequestlog',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='podcastrequestlog',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
    ]
