[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.9.7"]

[project]
authors = [
    {name = "Robert Huselius", email = "robert@huseli.us"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System",
    "Topic :: Multimedia :: Sound/Audio",
]
dependencies = [
    "audioop-lts; python_version >= '3.13'",
    "country_list",
    "django-filter>=25.2",
    "django-polymorphic",
    "django-rest-polymorphic>=0.1.10",
    "django",
    "djangorestframework-jsonapi[django-polymorphic,django-filter]",
    "djangorestframework",
    "drf-nested-routers>=0.95.0",
    "drf-spectacular-jsonapi",
    "drf-spectacular",
    "feedgen",
    "feedparser",
    "ffmpeg-python>=0.2.0",
    "geoip2",
    "iso639-lang",
    "klaatu-django",
    "markdownify",
    "martor",
    "pillow",
    "pydub",
    "python-dateutil",
    "python-slugify",
]
description = ""
license = "GPL-3.0-only"
license-files = ["LICENSE"]
name = "spodcat-backend"
readme = "README.md"
requires-python = ">=3.11"
version = "2.4.0"

[project.urls]
"Live example" = "https://podd.huseli.us"
Homepage = "https://github.com/Eboreg/spodcat-backend"
Issues = "https://github.com/Eboreg/spodcat-backend/issues"
Source = "https://github.com/Eboreg/spodcat-backend"

[dependency-groups]
dev = [
    "django-debug-toolbar",
    "django-extensions",
    "django-storages[azure]",
    "django-stubs",
    "djangorestframework-stubs",
    "ipdb",
    "ipython",
    "psycopg[binary]",
    "python-dotenv",
    "ruff>=0.15.10",
    "ty>=0.0.31",
    "types-markdown",
    "types-requests",
    "whitenoise",
]

[tool.uv]
exclude-newer = "P7D"

[tool.uv.build-backend]
module-name = "spodcat"
module-root = ""
source-exclude = ["test_env/**"]
wheel-exclude = ["test_env/**"]

[tool.pyright]
exclude = ["**/__pycache__", "node_modules", "build", "**/migrations", "**/.*", ".venv"]
ignore = [".venv"]
include = ["src"]
stubPath = "typings"
typeCheckingMode = "basic"

[tool.ruff]
exclude = [".venv", ".git", ".mypy_cache", "__pycache__", "build", "node_modules", "scratch.py"]
line-length = 120
show-fixes = true
target-version = "py312"

[tool.ruff.format]
docstring-code-line-length = 80
quote-style = "double"

[tool.ruff.lint]
ignore = ["E722", "B027", "B009"]
select = ["E", "F", "W", "B", "I"]

[tool.ruff.lint.isort]
combine-as-imports = true
default-section = "third-party"
lines-after-imports = 2
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
