# Generated by Django 6.0.6 on 2026-06-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spodcat", "0003_podcast_episode_rss_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastcontent",
            name="published",
            field=models.DateTimeField(default=None, null=True, verbose_name="published"),
        ),
    ]
