# Generated by Django 5.1.6 on 2025-02-20 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import podcasts.models
import podcasts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
                ('sub', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['cat', 'sub'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='', validators=[podcasts.validators.podcast_cover_validator])),
                ('cover_thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('tagline', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('language', models.CharField(blank=True, choices=podcasts.models.get_language_choices, default=None, max_length=5, null=True)),
                ('categories', models.ManyToManyField(to='podcasts.category')),
                ('owners', models.ManyToManyField(related_name='podcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('episode', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('audio_file', models.FileField(upload_to='')),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, verbose_name='duration')),
                ('dbfs_array', models.JSONField(blank=True, default=list)),
                ('audio_content_type', models.CharField(blank=True, max_length=100)),
                ('audio_file_length', models.PositiveIntegerField(blank=True)),
                ('slug', models.SlugField(default=None, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='podcasts.podcast')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='PodcastLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('facebook', 'Facebook'), ('patreon', 'Patreon'), ('discord', 'Discord')], max_length=10)),
                ('url', models.URLField()),
                ('label', models.CharField(max_length=100)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='podcasts.podcast')),
            ],
        ),
    ]
