# Generated by Django 5.1.6 on 2025-03-02 09:50

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models

import podcasts.models
import podcasts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastContent',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', mdeditor.fields.MDTextField(blank=True, default=None, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('description', mdeditor.fields.MDTextField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, default=None, height_field='cover_height', null=True, upload_to=podcasts.models.podcast_image_path, validators=[podcasts.validators.podcast_cover_validator], width_field='cover_width')),
                ('cover_height', models.PositiveIntegerField(default=None, null=True)),
                ('cover_width', models.PositiveIntegerField(default=None, null=True)),
                ('cover_thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_image_path)),
                ('banner', models.ImageField(blank=True, default=None, height_field='banner_height', null=True, upload_to=podcasts.models.podcast_image_path, width_field='banner_width')),
                ('banner_height', models.PositiveIntegerField(default=None, null=True)),
                ('banner_width', models.PositiveIntegerField(default=None, null=True)),
                ('favicon', models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_image_path)),
                ('favicon_content_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=podcasts.models.get_language_choices, default=None, max_length=5, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
                ('sub', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['cat', 'sub'],
                'indexes': [models.Index(fields=['cat', 'sub'], name='podcasts_ca_cat_aaa27d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('podcastcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='podcasts.podcastcontent')),
                ('number', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('audio_file', models.FileField(upload_to=podcasts.models.episode_audio_file_path)),
                ('duration_seconds', models.FloatField(blank=True, verbose_name='duration')),
                ('dbfs_array', models.JSONField(blank=True, default=list)),
                ('audio_content_type', models.CharField(blank=True, max_length=100)),
                ('audio_file_length', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('podcasts.podcastcontent',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('podcastcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='podcasts.podcastcontent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('podcasts.podcastcontent',),
        ),
        migrations.AddField(
            model_name='podcastcontent',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='podcasts.podcast'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(to='podcasts.category'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='owners',
            field=models.ManyToManyField(related_name='podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PodcastLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('facebook', 'Facebook'), ('patreon', 'Patreon'), ('discord', 'Discord'), ('apple', 'Apple'), ('android', 'Android'), ('spotify', 'Spotify'), ('itunes', 'Itunes')], default=None, max_length=10, null=True)),
                ('custom_icon', models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_link_icon_path)),
                ('url', models.URLField()),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('theme', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', max_length=10)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='podcasts.podcast')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='podcastcontent',
            index=models.Index(fields=['-published'], name='podcasts_po_publish_933abd_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['name'], name='podcasts_po_name_6bdde7_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastlink',
            index=models.Index(fields=['order'], name='podcasts_po_order_9ecd16_idx'),
        ),
    ]
