# Generated by Django 5.1.6 on 2025-04-07 15:15

from django.db import migrations, models

import podcasts.models.fields
import podcasts.models.podcast
import podcasts.models.podcast_link
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='banner',
            field=podcasts.models.fields.ImageField(blank=True, default=None, height_field='banner_height', help_text='Should be >= 960px wide and have aspect ratio 3:1.', null=True, upload_to=podcasts.models.podcast.podcast_image_path, verbose_name='Banner image', width_field='banner_width'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=podcasts.models.fields.ImageField(blank=True, default=None, height_field='cover_height', help_text="This is the round 'avatar' image.", null=True, upload_to=podcasts.models.podcast.podcast_image_path, validators=[podcasts.validators.podcast_cover_validator], width_field='cover_width'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_thumbnail',
            field=podcasts.models.fields.ImageField(blank=True, default=None, height_field='cover_thumbnail_height', null=True, upload_to=podcasts.models.podcast.podcast_image_path, width_field='cover_thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='favicon',
            field=podcasts.models.fields.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast.podcast_image_path),
        ),
        migrations.AlterField(
            model_name='podcastlink',
            name='custom_icon',
            field=podcasts.models.fields.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_link.podcast_link_icon_path),
        ),
    ]
