# Generated by Django 5.1.6 on 2025-04-04 02:59

import podcasts.models.podcast
import podcasts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='banner',
            field=models.ImageField(blank=True, default=None, height_field='banner_height', help_text='Should be >= 960px wide and have aspect ratio 3:1.', null=True, upload_to=podcasts.models.podcast.podcast_image_path, verbose_name='Banner image', width_field='banner_width'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='podcasts.category'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(blank=True, default=None, height_field='cover_height', help_text="This is the round 'avatar' image.", null=True, upload_to=podcasts.models.podcast.podcast_image_path, validators=[podcasts.validators.podcast_cover_validator], width_field='cover_width'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(help_text='Will be used in URLs.', primary_key=True, serialize=False, validators=[podcasts.validators.podcast_slug_validator]),
        ),
    ]
