# Generated by Django 5.1.6 on 2025-05-21 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcasts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='podcasts.category'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastlink',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='podcasts.podcast'),
        ),
        migrations.AddField(
            model_name='episodesong',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='podcasts.episode'),
        ),
        migrations.AddField(
            model_name='episodechapter',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='podcasts.episode'),
        ),
        migrations.AddIndex(
            model_name='podcastcontent',
            index=models.Index(fields=['-published'], name='podcasts_po_publish_933abd_idx'),
        ),
        migrations.AddConstraint(
            model_name='podcastcontent',
            constraint=models.UniqueConstraint(fields=('slug', 'podcast'), name='podcasts__podcastcontent__slug_podcast__uq'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['name'], name='podcasts_po_name_6bdde7_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastlink',
            index=models.Index(fields=['order'], name='podcasts_po_order_9ecd16_idx'),
        ),
        migrations.AddIndex(
            model_name='episodesong',
            index=models.Index(fields=['start_time'], name='podcasts_ep_start_t_232ae9_idx'),
        ),
    ]
