# Generated by Django 5.1.6 on 2025-02-19 22:09

from django.db import migrations


def migrate(apps, _):
    from podcasts.data import CATEGORIES

    Category = apps.get_model("podcasts", "Category")
    for cat, subs in CATEGORIES.items():
        Category.objects.create(cat=cat)
        for sub in subs:
            Category.objects.create(cat=cat, sub=sub)


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
