# Generated by Django 5.1.6 on 2025-04-07 17:20

from django.db import migrations, models

import podcasts.models.episode
import podcasts.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_episode_season_alter_podcast_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=podcasts.models.fields.ImageField(blank=True, default=None, height_field='image_height', null=True, upload_to=podcasts.models.episode.episode_image_path, width_field='image_width'),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_height',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_mimetype',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_thumbnail',
            field=podcasts.models.fields.ImageField(blank=True, default=None, height_field='image_thumbnail_height', null=True, upload_to=podcasts.models.episode.episode_image_path, width_field='image_thumbnail_width'),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_thumbnail_height',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_thumbnail_mimetype',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_thumbnail_width',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_width',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
