# Generated by Django 5.1.6 on 2025-04-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastlink',
            name='theme',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('boring', 'Boring')], default='primary', max_length=10),
        ),
    ]
