# Generated by Django 5.1.6 on 2025-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontent',
            name='slug',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
