# Generated by Django 5.1.6 on 2025-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name_font_family',
            field=models.CharField(choices=[('Anton', 'Anton'), ('Bauhaus 93', 'Bauhaus 93'), ('Deutsche Uncialis', 'Deutsche Uncialis'), ('Fascinate Inline', 'Fascinate Inline'), ('Futura Display BQ', 'Futura Display BQ'), ('Limelight', 'Limelight'), ('Lobster', 'Lobster'), ('Roboto Black', 'Roboto Black'), ('Roboto Serif Bold', 'Roboto Serif Bold'), ('Unifraktur Cook', 'Unifraktur Cook')], default='Unifraktur Cook', max_length=50),
        ),
    ]
