# Generated by Django 5.1.6 on 2025-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastcontent',
            options={'get_latest_by': 'published', 'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_file_length',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration_seconds',
            field=models.FloatField(blank=True, db_index=True, default=0.0, verbose_name='duration'),
        ),
    ]
