# Generated by Django 5.1.6 on 2025-03-07 10:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_populate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
                'indexes': [models.Index(fields=['name'], name='podcasts_ar_name_0f4045_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='podcasts__artist__name__uq')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('timestamp', models.PositiveIntegerField()),
                ('artists', models.ManyToManyField(blank=True, related_name='songs', to='podcasts.artist')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='podcasts.episode')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='podcasts_ep_timesta_51d438_idx')],
            },
        ),
    ]
