# Generated by Django 5.1.6 on 2025-02-21 16:21

from django.db import migrations, models

import podcasts.models
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_populate_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-episode', '-published']},
        ),
        migrations.AddField(
            model_name='podcast',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_image_path),
        ),
        migrations.AddField(
            model_name='podcast',
            name='favicon_content_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(upload_to=podcasts.models.episode_audio_file_path),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_image_path),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_image_path, validators=[podcasts.validators.podcast_cover_validator]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast_image_path),
        ),
    ]
