# Generated by Django 5.1.6 on 2025-03-07 15:57

from django.db import migrations, models

import podcasts.models.podcast
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_artist_episodesong'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cover_thumbnail_height',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover_thumbnail_width',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, default=None, height_field='cover_thumbnail_height', null=True, upload_to=podcasts.models.podcast.podcast_image_path, width_field='cover_thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, validators=[podcasts.validators.podcast_slug_validator]),
        ),
    ]
