# Generated by Django 5.1.6 on 2025-04-09 01:42

import uuid

from django.db import migrations, models

import podcasts.models.challenge


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('term1', models.PositiveSmallIntegerField(default=podcasts.models.challenge.generate_term)),
                ('term2', models.PositiveSmallIntegerField(default=podcasts.models.challenge.generate_term)),
            ],
        ),
    ]
