# Generated by Django 5.1.6 on 2025-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_episode_image_episode_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='name_font_family',
            field=models.CharField(choices=[('Anton', 'Anton'), ('Deutsche Uncialis', 'Deutsche Uncialis'), ('Fascinate Inline', 'Fascinate Inline'), ('Futura Display BQ', 'Futura Display BQ'), ('Limelight', 'Limelight'), ('Lobster', 'Lobster'), ('Roboto Black', 'Roboto Black'), ('Roboto Serif Bold', 'Roboto Serif Bold'), ('Unifraktur Cook', 'Unifraktur Cook')], default='Unifraktur Cook', max_length=50),
        ),
        migrations.AddField(
            model_name='podcast',
            name='name_font_size',
            field=models.PositiveIntegerField(default=60, help_text='In pixels. Will be scaled down on small screens.'),
        ),
    ]
