# Generated by Django 5.1.6 on 2025-03-01 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_podcastcontent_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('podcastcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='podcasts.podcastcontent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('podcasts.podcastcontent',),
        ),
    ]
