# Generated by Django 5.1.6 on 2025-04-23 20:52

from django.db import migrations, models

import podcasts.models.podcast_content


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_comment_name_alter_podcast_name_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontent',
            name='published',
            field=models.DateField(default=podcasts.models.podcast_content.today),
        ),
    ]
