# Generated by Django 5.1.6 on 2025-02-21 20:12

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_episode_options_podcast_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, default=None, null=True),
        ),
    ]
