# Generated by Django 5.1.6 on 2025-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_podcastlink_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='custom_guid',
            field=models.UUIDField(blank=True, default=None, help_text="Don't set if you don't know what you're doing. Ref: https://podcasting2.org/podcast-namespace/tags/guid", null=True, verbose_name='Custom GUID'),
        ),
    ]
