# Generated by Django 5.1.6 on 2025-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_name_font_family_podcast_name_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='name_font_size',
            field=models.CharField(choices=[('small', 'small'), ('normal', 'normal'), ('large', 'large')], default='normal', max_length=10),
        ),
    ]
