# Generated by Django 5.1.6 on 2025-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
