# Generated by Django 5.1.6 on 2025-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_challenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='podcast',
            name='enable_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='require_comment_approval',
            field=models.BooleanField(default=True),
        ),
    ]
