# Generated by Django 5.1.6 on 2025-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_cover_thumbnail_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cover_mimetype',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover_thumbnail_mimetype',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
