# Generated by Django 5.1.6 on 2025-04-11 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_comment_options_podcast_enable_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='owned_podcasts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
