# Generated by Django 5.1.6 on 2025-05-09 13:44

from django.db import migrations

import utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodesong',
            name='timestamp',
            field=utils.model_fields.TimestampField(),
        ),
    ]
