# Generated by Django 5.1.6 on 2025-05-09 14:28

import django.db.models.deletion
from django.db import migrations, models

import podcasts.models.episode_chapter
import utils.model_fields
import utils.model_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_episodesong_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', utils.model_fields.TimestampField()),
                ('end_time', utils.model_fields.TimestampField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.episode_chapter.episode_chapter_image_path)),
                ('url', models.URLField(default=None, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='podcasts.episode')),
            ],
            options={
                'ordering': ['start_time'],
            },
            bases=(utils.model_mixin.ModelMixin, models.Model),
        ),
    ]
