# Generated by Django 5.1.6 on 2025-04-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_podcast_owner_alter_podcast_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='owners',
            new_name='authors',
        ),
    ]
