# Generated by Django 5.1.6 on 2025-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_episodechapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodesong',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveIndex(
            model_name='episodesong',
            name='podcasts_ep_timesta_51d438_idx',
        ),
        migrations.RenameField(
            model_name='episodesong',
            old_name='timestamp',
            new_name='start_time',
        ),
        migrations.AddIndex(
            model_name='episodesong',
            index=models.Index(fields=['start_time'], name='podcasts_ep_start_t_232ae9_idx'),
        ),
    ]
