# Generated by Django 5.1.6 on 2025-04-07 20:30

import podcasts.models.episode
import podcasts.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_rename_owners_podcast_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=podcasts.models.fields.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.episode.episode_image_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_thumbnail',
            field=podcasts.models.fields.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.episode.episode_image_path),
        ),
    ]
