# Generated by Django 5.1.6 on 2025-04-07 20:46

import podcasts.models.fields
import podcasts.models.podcast
import podcasts.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_alter_episode_image_alter_episode_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='banner',
            field=podcasts.models.fields.ImageField(blank=True, default=None, help_text='Should be >= 960px wide and have aspect ratio 3:1.', null=True, upload_to=podcasts.models.podcast.podcast_image_path, verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=podcasts.models.fields.ImageField(blank=True, default=None, help_text="This is the round 'avatar' image.", null=True, upload_to=podcasts.models.podcast.podcast_image_path, validators=[podcasts.validators.podcast_cover_validator]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_thumbnail',
            field=podcasts.models.fields.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.podcast.podcast_image_path),
        ),
    ]
