# Generated by Django 5.1.6 on 2025-05-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_alter_episodesong_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodesong',
            old_name='name',
            new_name='title',
        ),
    ]
