# Generated by Django 5.1.6 on 2025-05-09 15:09

from django.db import migrations, models

import podcasts.models.episode_chapter
import utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_rename_name_episodesong_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesong',
            name='end_time',
            field=utils.model_fields.TimestampField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='episodesong',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=podcasts.models.episode_chapter.episode_chapter_image_path),
        ),
        migrations.AddField(
            model_name='episodesong',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
