# Generated by Django 5.1.6 on 2025-05-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_episodesong_end_time_episodesong_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodechapter',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='episodesong',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
