# Generated by Django 5.2.3 on 2025-07-02 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='spodcat.category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='podcastcontent',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='spodcat.podcast', verbose_name='podcast'),
        ),
        migrations.AlterField(
            model_name='podcastlink',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='spodcat.podcast', verbose_name='podcast'),
        ),
    ]
