# Generated by Django 5.2.3 on 2025-07-02 12:04

import spodcat.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0002_alter_podcast_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.episode_audio_file_path, verbose_name='audio file'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.episode_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_thumbnail',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.episode_image_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='episodechapter',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.episode_chapter_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episodesong',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.episode_chapter_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='banner',
            field=models.ImageField(blank=True, default=None, help_text='Should be >= 960px wide and have aspect ratio 3:1.', max_length=300, null=True, upload_to=spodcat.models.functions.podcast_banner_path, verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(blank=True, default=None, help_text="This is the round 'avatar' image. It should ideally have height and width >= 1400px.", max_length=300, null=True, upload_to=spodcat.models.functions.podcast_cover_path, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.podcast_cover_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='favicon',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.podcast_favicon_path, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='podcastlink',
            name='custom_icon',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to=spodcat.models.functions.podcast_link_icon_path, verbose_name='custom icon'),
        ),
    ]
