# Generated by Django 5.2.3 on 2025-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0002_fontface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontface',
            name='format',
            field=models.CharField(choices=[('truetype', 'Truetype'), ('woff', 'WOFF 1.0'), ('woff2', 'WOFF 2.0'), ('opentype', 'Opentype'), ('collection', 'Opentype Collection'), ('embedded-opentype', 'Embedded Opentype'), ('svg', 'SVG font (deprecated)')], default=None, max_length=20, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='fontface',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='name'),
        ),
    ]
