# Generated by Django 5.2.3 on 2025-07-02 12:23

import django.db.models.deletion
from django.db import migrations, models


def pre_migrate(apps, schema_editor):
    Challenge = apps.get_model("spodcat", "Challenge")
    Challenge.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0003_alter_episode_audio_file_alter_episode_image_and_more'),
    ]

    operations = [
        migrations.RunPython(pre_migrate, migrations.RunPython.noop),
        migrations.AddField(
            model_name='challenge',
            name='podcast',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spodcat.podcast'),
            preserve_default=False,
        ),
    ]
