# Generated by Django 5.2.3 on 2025-07-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0003_alter_fontface_format_alter_fontface_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontface',
            options={'verbose_name': 'font face', 'verbose_name_plural': 'font faces'},
        ),
        migrations.AlterField(
            model_name='fontface',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='name'),
        ),
    ]
