# Generated by Django 5.2.3 on 2025-07-02 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0004_alter_fontface_options_alter_fontface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontface',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
