# Generated by Django 5.2.3 on 2025-07-03 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0005_fontface_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='name_font_face',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spodcat.fontface', verbose_name='name font face'),
        ),
    ]
