# Generated by Django 5.2.3 on 2025-07-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0006_podcast_name_font_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='name_font_face',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spodcat.fontface', verbose_name='name font face'),
        ),
    ]
