# Generated by Django 5.2.3 on 2025-07-03 04:27

from django.db import migrations, models

import spodcat.models.functions


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0007_alter_podcast_name_font_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.episode_audio_file_storage, upload_to=spodcat.models.functions.episode_audio_file_upload_to, verbose_name='audio file'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.episode_image_storage, upload_to=spodcat.models.functions.episode_image_upload_to, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_thumbnail',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.episode_image_thumbnail_storage, upload_to=spodcat.models.functions.episode_image_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='episodechapter',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.episode_chapter_image_storage, upload_to=spodcat.models.functions.episode_chapter_image_upload_to, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episodesong',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.episode_chapter_image_storage, upload_to=spodcat.models.functions.episode_chapter_image_upload_to, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='fontface',
            name='file',
            field=models.FileField(storage=spodcat.models.functions.fontface_file_storage, upload_to=spodcat.models.functions.fontface_file_upload_to, verbose_name='font file'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='banner',
            field=models.ImageField(blank=True, default=None, help_text='Should be >= 960px wide and have aspect ratio 3:1.', max_length=300, null=True, storage=spodcat.models.functions.podcast_banner_storage, upload_to=spodcat.models.functions.podcast_banner_upload_to, verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(blank=True, default=None, help_text="This is the round 'avatar' image. It should ideally have height and width >= 1400px.", max_length=300, null=True, storage=spodcat.models.functions.podcast_cover_storage, upload_to=spodcat.models.functions.podcast_cover_upload_to, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.podcast_cover_thumbnail_storage, upload_to=spodcat.models.functions.podcast_cover_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='favicon',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.podcast_favicon_storage, upload_to=spodcat.models.functions.podcast_favicon_upload_to, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='podcastlink',
            name='custom_icon',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, storage=spodcat.models.functions.podcast_link_icon_storage, upload_to=spodcat.models.functions.podcast_link_icon_upload_to, verbose_name='custom icon'),
        ),
    ]
