# Generated by Django 5.2.3 on 2025-07-03 06:43

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spodcat', '0008_alter_episode_audio_file_alter_episode_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontface',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'font face', 'verbose_name_plural': 'font faces'},
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='name_font_family',
        ),
    ]
